### ISSUE TITLE
Error returns wrong starting year 

### ISSUE THREAD

**Issue by Nastaliss** [frgfm/validate-python-headers#17]
### Bug description

The error message for invalid headers prints `year-1 - year` as suggestion

### Code snippet to reproduce the bug

python /validate_headers.py Pyronear 2022 --license Apache-2.0 --folders src,client,.github --ignore-files version.py,__init__.py --ignore-folders client/tests/,src/tests/ --license-notice in the repository https://github.com/pyronear/pyro-storage

### Error traceback

The error message will be :
 ```
 Your header should look like:

# Copyright (C) 2023-2024, Pyronear.

# This program is licensed under the Apache License 2.0.
```
However, the message should be :
```
 Your header should look like:

# Copyright (C) 2022-2024, Pyronear.

# This program is licensed under the Apache License 2.0.
```
as the starting year is 2022

### Environment

Ran in a github action, irrelevant

**Comment by frgfm** [comment]
Considering this message is common to all the detected files, would this suffice?
```
 Your header should look like:

# Copyright (C) <FILE_CREATION_YEAR>-2024, Pyronear.

# This program is licensed under the Apache License 2.0.
```

Because this isn't necessarily uniform in the codebase

**Comment by Nastaliss** [comment]
Yep this would work :)
